### ISSUE TITLE
DEBUG mode and build information

### ISSUE THREAD

**Issue by gedger** [cjcliffe/CubicSDR#431]
Is it possible to see the SoapySDR debug messages from CubicSDR, i.e. set SOAPY_SDR_LOG_LEVEL=DEBUG?

Is it possible to see the versions of the various SoapySDR modules and libraries that CubicSDR is built with? I noticed a note in the SoapySDRPlay module docs which says including this will force use of an older version of SoapySDR, perhaps add information to the help about?

**Comment by cjcliffe** [comment]
Ahoy @gedger 

Just a note to start with; there's a few command line options available for CubicSDR:
```
cjmacbook:~ ccliffe$ /Applications/CubicSDR.app/Contents/MacOS/CubicSDR --help
Usage: CubicSDR [-h] [-c <str>] [-m <str>] [-b]
  -h, --help         	Command line parameter help
  -c, --config=<str> 	Specify a named configuration to use, i.e. '-c ham'
  -m, --modpath=<str>	Load modules from suppplied path, i.e. '-m ~/SoapyMods/'
  -b, --bundled      	Use bundled SoapySDR modules first instead of local.
```
Using the -b flag I believe has no effect at the moment but setting a module path allows you to use your own SoapySDR module builds by specifying the path.

For extra Soapy debugging you can also set the environment variable "SOAPY_SDR_LOG_LEVEL" to "DEBUG" in Windows environment editor, or run it prefixed from the command line in OSX/Linux:
```
cjmacbook:~ ccliffe$ SOAPY_SDR_LOG_LEVEL=DEBUG /Applications/CubicSDR.app/Contents/MacOS/CubicSDR
```
With that you'll get a pile of Soapy debug messages at runtime

Note in windows you'll need to pipe it to file with something like:
```
CubicSDR.exe > cubicsdr_log1.txt
```
to see the output somewhere as it's nullified otherwise.

Will leave this open as a reminder to document.
