### ISSUE TITLE
Unable to change waterfall speed

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#454]
The waterfall speed slider doesn't work. See https://we.tl/JaL8PL8yG6 (wetransfer link to video file).

**Comment by cjcliffe** [comment]
@Toontje link expired for this; but I'm guessing this might be a <=500KHz issue again?  If there isn't enough input data for additional waterfall lines it will cap at the maximum possible rate.

This is also true when you zoom in since it's decimating the signal more and more as you zoom and the amount of bandwidth available for waterfall lines is reduced and will cap at the maximum.

**Comment by Toontje** [comment]
Ok, clear.
