### ISSUE TITLE
Compiling wxWidgets on High Sierra 10.13.2 - fails

### ISSUE THREAD

**Issue by blrichwine** [cjcliffe/CubicSDR#603]
Anyone know how to compile wxWidgets on High Sierra? I'm using a fully updated osx build and the latest MacPort with updates. I tried both 3.1.0 and 3.0.3. Both fail with the same error:

./src/osx/core/utilsexc_base.cpp:74:13: error: use of undeclared identifier 'verify_noerr'
            verify_noerr(Gestalt(gestaltSystemVersion, &sUMASystemVersion));
            ^
1 error generated.

Thanks for any help

**Comment by EtherealT** [comment]
I'm also having the exact problem

**Comment by righthalfplane** [comment]
I was able to compile wxWidgets 3.0.3 on High Sierra by first defining a cpp flag -

CPPFLAGS=-D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=1 

and then

./configure --prefix=/usr/local/wxWidgets --with-macosx-version-min=10.9

This built what I needed

**Comment by righthalfplane** [comment]
wxWidgets-3.1.0 on High Sierra required one additional option to get it to install using tcsh

setenv CPPFLAGS -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=1

./configure --prefix=/usr/local/wxWidgets --with-macosx-version-min=10.9 --disable-mediactrl

make -j 8

sudo make install

**Comment by KaungZawHtet** [comment]
How and where to define CPP_Flag

**Comment by righthalfplane** [comment]
With tcsh you set the environment variable CPPFLAGS with -

setenv CPPFLAGS -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=1

With sh you set the environment variable CPPFLAGS with -

CPPFLAGS=-D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=1; export CPPFLAGS

**Comment by mohamad325** [comment]
Thanks for mailing

Mohamad asadi.

On Mar 4, 2018 22:13, "righthalfplane" <notifications@github.com> wrote:

With tcsh you set the environment variable CPPFLAGS with -

setenv CPPFLAGS -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=1

With sh you set the environment variable CPPFLAGS with -

CPPFLAGS=-D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=1; export
CPPFLAGS

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cjcliffe/CubicSDR/issues/603#issuecomment-370252698>,
or mute the thread

**Comment by cjcliffe** [comment]
Can anyone confirm this is still an issue with wxWidgets-3.1.1?  

I've been reluctant to install High Sierra here due to the multitude of issues I've read online plus the two macs at work that both failed horribly during the upgrade and had to be reformatted, reinstalled and then migrated from TC backups.

**Comment by vsonnier** [comment]
Too old issue, with outdated wxWidgets and Cubic. Users were able to build for Mac since then.
