### ISSUE TITLE
getFrequency feedback

### ISSUE THREAD

**Issue by mipac** [cjcliffe/CubicSDR#642]
Hi,

The call to device->getFrequency(...) is commented in the soapySDR thread code.
Is there a way to feedback the real freq to the gui?

Thanks a lot!

Michel

**Comment by vsonnier** [comment]
@mipac That was probably a leftover of some test code. The `getFrequency()` is not needed, because the frequency is set by `setFrequency` and considered constant afterwards, so there is really no need to re-read the getter. 
The getter is probably just re-reading an internal variable previously set by the setter call anyway.
