### ISSUE TITLE
WA9ZPM Mike

### ISSUE THREAD

**Issue by Mikejkiley** [cjcliffe/CubicSDR#643]
I have cubicSDR v 0.2.2, which I downloaded, expanded, and wrote into an SD card for use in a Rasberry pi3 computer, using an RSP 2 receiver.  However, all I get when I launch the program is blank spectrum and waterfall displays, and no sound.  Also, I get no drop-down menus for the Settings or Sample Rate tabs at the upper left of the screen, although the tab labels turn blue when clicked on.  When the program launches, a box opens saying loading soapySDR modules and says the RSP2, with serial number, is present.  clicking on the START button does nothing.  How do I get this working?  I am only interested in a locally operated, single modem, receiver.

**Comment by vsonnier** [comment]
@Mikejkiley  Hello ! First thing, your version is outdated so no support will be provided for such version, the differences with the current v0.23 are to big to wast time on that.
Next, go to #607 and  #639 for questions on how to handle CubicSDR on RasberryPi.
Since you own RSP2, the simplest way is to use the latest Pi v0.3 image here: https://www.sdrplay.com/downloads/
