### ISSUE TITLE
frequency changes but audio doesn't

### ISSUE THREAD

**Issue by invisibleman1962** [cjcliffe/CubicSDR#656]
Hello, I'm hoping someone here can suggest a solution to this problem.

I'm using CubicSDR with SDRplay RSP1A.  I had been using CubicSDR 0.2.3 and then downloaded and installed 0.2.4 today. However, the same problem is still occurring. 

The problem being that even after I've changed frequencies from one transmission to another, the 'frequency' display shows the frequency has changed, but the 'audio' from the first frequency is still playing.

For example, let's say I'm listening to a broadcast transmission on 7410 KHz. When I go to a different frequency, say, 5000 KHz,  rather than hearing the audio on 5000 KHz, I still hear the audio on 7410 KHz.  So, while the display says I've changed frequency, the audio doesn't change.

**Comment by vsonnier** [comment]
Hello ! What you observe is perfectly normal for CubicSDR and SDR handling in general: there is a distinction to make between the 'tuned frequency' a.k.a. 'central frequency', a.k.a 'LO frequency', and the 'frequency' of a particular demod you created between = [central frequency - sample rate / 2; central frequency + sample rate / 2].
As long as you change 'frequency' of a particular demod so that this new 'frequency' is still in the previous  [central frequency - sample rate / 2; central frequency + sample rate / 2] interval, you'll be able to listen to it.

Now if you really want the 'frequency' of the demod to be __fixed__ relative to the 'central frequency' and move with it, you have to activate Delta Lock (V) for it.

See [CubicSDR Manual](http://cubicsdr.readthedocs.io/en/latest/) for some more details on CubicSDR operation and also #556.
