### ISSUE TITLE
CubicSDR CubicSDR-0.2.4 in not work

### ISSUE THREAD

**Issue by Abdula-2015** [cjcliffe/CubicSDR#683]
I used **CubicSDR-0.2.4-x86_64.AppImage**. **Debian 9/32 bit** and dongl **RTL2832U+R820T**.

CubicSDR starts, but does not work.
No reception, no waterfall -

![cubicsdr_0 2 4_not_worked](https://user-images.githubusercontent.com/12355404/46745708-45aed500-ccb6-11e8-99ad-f4c9068bb478.png)

**But Gqrx works great!**

![gqrx_2 6](https://user-images.githubusercontent.com/12355404/46745730-51020080-ccb6-11e8-942c-1eb50b115fb5.png)

Why does not work CubicSDR ???

**Comment by Osirus126** [comment]
I have a feeling you are using the rtl_tcp application for a SDR server but you must use SoapySDRServer for CubicSDR.

**Comment by NotAFile** [comment]
I have the same issue. CubicSDR from my repos works fine, but the AppImage shows no output.

While it's running, it shows the following output:

```
SDRThread::readStream(): 3.1 iqDataOutQueue output queue is full, discard processing of the batch...
SDRThread::readStream(): 2. SoapySDR read failed with code: -1
```

**Comment by Abdula-2015** [comment]
I do not understand why CubicSDR was made.
I use Gqrx - it works!

CubicSDR creates fatal problems, but developers are lazy and do not help.

Qqrx is **better**! And I return to it.

**Comment by NotAFile** [comment]
@Abdula-2015 You're being extremely rude here. Cjcliffe has put a lot of free time into making this and making it available for free. That is anything but lazy. People like you complaining and insulting them is a reason why so many developers feel frustrated and give up on great projects.

**Comment by vsonnier** [comment]
Dear @Abdula-2015, since your are *not* lazy as the developers here, as shows your commit history (*sarcarsm*) you can always compile the whole thing from scratch as the Wiki and multiple issues already describes. 
As for Applmage in general, it just a convenience that *may* work if all the dependencies are satisfied on the running machine. And the correct drivers and libraries installed. 

Finally, since we are lazy but still not telepaths, we cannot guess the multitude of Linux variants out there  so the condition to be helped is to describe your system kernel, distro, *SDR drivers*, packages, SDR device you want to listen, extensive logs of Cubic ...etc.

Otherwise on Linux, the statement  "Doesn't work on my [random Linux distro name here] is just, well, spam.

Please continue on #682 providing the above info as described, for those still interested.
