### ISSUE TITLE
WTF is the latest version to D/l and why is it so hard to keep that information at the front of this page?

### ISSUE THREAD

**Issue by MiamiC70** [cjcliffe/CubicSDR#690]
WTF is the latest version to D/l and why is it so hard to keep that information at the front of this page?
Says v2.4.0 yet I have v2.5.0 loaded from Nov 18th which is nowhere to be found on here.

Why is is so go damn hard to be professional? you want to charge money go ahead and I'll pay but this is frustrating beyond belief.

**Comment by parkerlreed** [comment]
... https://github.com/cjcliffe/CubicSDR/releases

Lists 2.5. What exactly is the issue? The readme lists that link for the releases.

**Comment by cjcliffe** [comment]
@MiamiC70 I usually wait until there's been time for the new release to be tested by the more eager users checking GitHub before publishing it on the website.  Since 0.2.5 release I've seen a few issues that were keeping me from promoting it to the recommended version for all platforms and have been too busy with other work (amongst finding and moving to a new place) to put proper focus on CubicSDR issues and builds.

But I'm set up at my new place now, have finally unpacked radios and antennas last week and will be working on CubicSDR more regularly again this year.

I can also assure you there hasn't been any attempt to be professional and I hope to keep it free forever :)

Cheers.
