### ISSUE TITLE
Not Found (insert SDR name here)

### ISSUE THREAD

**Issue by TheButterZone** [cjcliffe/CubicSDR#734]
![Screen Shot 2019-05-21 at 12 59 52](https://user-images.githubusercontent.com/2625857/58126795-9ed5d400-7bc8-11e9-84d7-d81fc96b9177.png)

Are they lying, or what exact format is required to get CubicSDR to connect to the green AirSpy or RTL-SDR servers on https://airspy.com/directory/ ?

**Comment by jazzkutya** [comment]
Hi,

they are not lying. Airspy servers work only with sdr# while the airspy device itself should work with cubicsdr (locally, not over the network). Those servers use an sdr#-specific protocol. Cubicsdr can use devices over the network with SoapySDRRemote https://github.com/pothosware/SoapyRemote/wiki but this is a different solution for a similar (not same) problem and they are not compatible.

**Comment by TheButterZone** [comment]
<SA

> 6BSS-Mike> thats for airspy HW, not the spy server network
> <mzs> *agree SA6BSS-Mike* I just searched through the source code for cubicsdr on github and no it does not support spyservers. It could be added if they used the code from https://github.com/opensatelliteproject/xritdemod/tree/master/demodulator/src

**Comment by vsonnier** [comment]
Hello there, @jazzkutya is right CubicSDR is compatible only with SoapySDRRemote because it allows interfacing with distant hardware the same way as local hardware using the SoapySDR API. The thing is, CubicSDR usage of this API is deeply interlaced, and I don't see it using "yet another API".

On the SoapySDR side itself SpyServer support has already been suggested for instance here https://github.com/pothosware/SoapySDR/issues/156 and suggestions may come there. It is indeed better and easier to make SoapySDRRemote or why not a new "SoapySDRSpyServer" module support the new devices than plugin another code in the client CubicSDR side of things.
