### ISSUE TITLE
CubicSDR client vs Soapy Remote

### ISSUE THREAD

**Issue by JorgeASantos** [cjcliffe/CubicSDR#783]
Hi, 

See detailed comment on CubicSDR, included in my just posted:
Note2_RPi4_V6.3__The temperature of Pi 
web page: radioforcruisers.blogspot.com

Feel free to send me comments, suggestions or proposals of correction.
 BW"
Jorge

**Comment by vsonnier** [comment]
@JorgeASantos Thanks fot the link. A more persistent link would be: https://radioforcruisers.blogspot.com/2020/01/note2rpi4v63the-temperature-of-pi.html

However, for the general well-behaving there, please do not simply post links to wall of texts peeple was explected to read and understand the issue supposely reported. 

Based on this what this article is about ? About trying to run CubicSDR on a Pi (again...sigh) and all the problems that come to it. At the risk of being blunt, there is only two points to consider:

- Pi are crap CPU wise relative to what DSP is supposed to be. It is a miracle it was usable **at all** on a host like this and a testament of CubicSDR and liquid-dsp efficiency. There are already a ton of issues reported there, just refer to them but the problem is not CubicSDR here, the lack of power is.
- Pi connections are crap. Or rather, the I/Q stream that need to be pushed in a Wifi/LAN is very important and all limitations and defficiencies of the interfaces are likely to show there. Likewise, a ton of issues and questions exist already here or on SoapyRemote side (https://github.com/pothosware/SoapyRemote/issues)

The final word is: If you try Cubic on Pi, either locally or remotely using SoapyRemote, you have to experiment yourself but know that the software itself is solid.  Pis are borderline and so out-of-support for such applications.
