### ISSUE TITLE
No sound device selectable on Windows 10

### ISSUE THREAD

**Issue by Starhowl** [cjcliffe/CubicSDR#894]
I have no option to select a sound device and there is no audio output at the same time while being tuned in to a FM radio-station:
![Capture](https://user-images.githubusercontent.com/54993307/119251172-65fcdb00-bba5-11eb-88f6-a85e7c84153f.PNG)

**Comment by vsonnier** [comment]
Having 'FM slected' in that screenshot do not mean you are indeed `tuned into a FM radio station`

Since you are on Windows 10 the only way you can have your situation is that you probably didn't create a dmod on the waterfall. See https://cubicsdr.readthedocs.io/en/latest/ for more info.

Please provide a full screen screenshot of your problem.

**Comment by vsonnier** [comment]
Issue is too old, no feedback : closing.
